nerdfont: true
agent: pi
sandbox:
  enabled: true
  backend: container
  image: workmux-dev:latest
  container:
    runtime: apple-container
panes:
  - focus: true
    command: >-
      pi --no-extensions
